drop table if exists estado;
drop table if exists cidade;
create table estado(ibge int, nome varchar(100), sigla varchar(2), regiao varchar(80), municipios int);
insert into estado(ibge, nome, sigla, regiao, municipios) values(11, 'Rondônia', 'RO', 'Região Norte', 52);
insert into estado(ibge, nome, sigla, regiao, municipios) values(12, 'Acre', 'AC', 'Região Norte', 22);
insert into estado(ibge, nome, sigla, regiao, municipios) values(13, 'Amazonas', 'AM', 'Região Norte', 62);
insert into estado(ibge, nome, sigla, regiao, municipios) values(14, 'Roraima', 'RR', 'Região Norte', 15);
insert into estado(ibge, nome, sigla, regiao, municipios) values(15, 'Pará', 'PA', 'Região Norte', 144);
insert into estado(ibge, nome, sigla, regiao, municipios) values(16, 'Amapá', 'AP', 'Região Norte', 16);
insert into estado(ibge, nome, sigla, regiao, municipios) values(17, 'Tocantins', 'TO', 'Região Norte', 139);
insert into estado(ibge, nome, sigla, regiao, municipios) values(21, 'Maranhão', 'MA', 'Região Nordeste', 217);
insert into estado(ibge, nome, sigla, regiao, municipios) values(22, 'Piauí', 'PI', 'Região Nordeste', 224);
insert into estado(ibge, nome, sigla, regiao, municipios) values(23, 'Ceará', 'CE', 'Região Nordeste', 184);
insert into estado(ibge, nome, sigla, regiao, municipios) values(24, 'Rio Grande do Norte', 'RN', 'Região Nordeste', 167);
insert into estado(ibge, nome, sigla, regiao, municipios) values(25, 'Paraíba', 'PB', 'Região Nordeste', 223);
insert into estado(ibge, nome, sigla, regiao, municipios) values(26, 'Pernambuco', 'PE', 'Região Nordeste', 185);
insert into estado(ibge, nome, sigla, regiao, municipios) values(27, 'Alagoas', 'AL', 'Região Nordeste', 102);
insert into estado(ibge, nome, sigla, regiao, municipios) values(28, 'Sergipe', 'SE', 'Região Nordeste', 75);
insert into estado(ibge, nome, sigla, regiao, municipios) values(29, 'Bahia', 'BA', 'Região Nordeste', 417);
insert into estado(ibge, nome, sigla, regiao, municipios) values(31, 'Minas Gerais', 'MG', 'Região Sudeste', 853);
insert into estado(ibge, nome, sigla, regiao, municipios) values(32, 'Espírito Santo', 'ES', 'Região Sudeste', 78);
insert into estado(ibge, nome, sigla, regiao, municipios) values(33, 'Rio de Janeiro', 'RJ', 'Região Sudeste', 92);
insert into estado(ibge, nome, sigla, regiao, municipios) values(35, 'São Paulo', 'SP', 'Região Sudeste', 645);
insert into estado(ibge, nome, sigla, regiao, municipios) values(41, 'Paraná', 'PR', 'Região Sul', 399);
insert into estado(ibge, nome, sigla, regiao, municipios) values(42, 'Santa Catarina', 'SC', 'Região Sul', 295);
insert into estado(ibge, nome, sigla, regiao, municipios) values(43, 'Rio Grande do Sul', 'RS', 'Região Sul', 497);
insert into estado(ibge, nome, sigla, regiao, municipios) values(50, 'Mato Grosso do Sul', 'MS', 'Região Centro-Oeste', 79);
insert into estado(ibge, nome, sigla, regiao, municipios) values(51, 'Mato Grosso', 'MT', 'Região Centro-Oeste', 141);
insert into estado(ibge, nome, sigla, regiao, municipios) values(52, 'Goiás', 'GO', 'Região Centro-Oeste', 246);
insert into estado(ibge, nome, sigla, regiao, municipios) values(53, 'Distrito Federal', 'DF', 'Região Centro-Oeste', 1);
create table cidade(ibge int, nome varchar(100), estado varchar(2), regiao varchar(100), populacao int, porte varchar(80));
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110001, 'Alta Floresta D´oeste', 'RO', 'Região Norte', 24392, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110002, 'Ariquemes', 'RO', 'Região Norte', 90353, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110003, 'Cabixi', 'RO', 'Região Norte', 6313, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110004, 'Cacoal', 'RO', 'Região Norte', 78574, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110005, 'Cerejeiras', 'RO', 'Região Norte', 17029, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110006, 'Colorado do Oeste', 'RO', 'Região Norte', 18591, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110007, 'Corumbiara', 'RO', 'Região Norte', 8783, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110008, 'Costa Marques', 'RO', 'Região Norte', 13678, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110009, 'Espigão D´oeste', 'RO', 'Região Norte', 28729, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110010, 'Guajará-mirim', 'RO', 'Região Norte', 41656, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110011, 'Jaru', 'RO', 'Região Norte', 52005, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110012, 'Ji-paraná', 'RO', 'Região Norte', 116610, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110013, 'Machadinho D´oeste', 'RO', 'Região Norte', 31135, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110014, 'Nova Brasilândia D´oeste', 'RO', 'Região Norte', 19874, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110015, 'Ouro Preto do Oeste', 'RO', 'Região Norte', 37928, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110018, 'Pimenta Bueno', 'RO', 'Região Norte', 33822, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110020, 'Porto Velho', 'RO', 'Região Norte', 428527, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110025, 'Presidente Médici', 'RO', 'Região Norte', 22319, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110026, 'Rio Crespo', 'RO', 'Região Norte', 3316, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110028, 'Rolim de Moura', 'RO', 'Região Norte', 50648, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110029, 'Santa Luzia D´oeste', 'RO', 'Região Norte', 8886, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110030, 'Vilhena', 'RO', 'Região Norte', 76202, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110032, 'São Miguel do Guaporé', 'RO', 'Região Norte', 21828, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110033, 'Nova Mamoré', 'RO', 'Região Norte', 22546, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110148, 'São Felipe D´oeste', 'RO', 'Região Norte', 6018, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110149, 'São Francisco do Guaporé', 'RO', 'Região Norte', 16035, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110150, 'Seringueiras', 'RO', 'Região Norte', 11629, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110155, 'Teixeirópolis', 'RO', 'Região Norte', 4888, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110160, 'Theobroma', 'RO', 'Região Norte', 10649, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110170, 'Urupá', 'RO', 'Região Norte', 12974, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110175, 'Vale do Anari', 'RO', 'Região Norte', 9384, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(110180, 'Vale do Paraíso', 'RO', 'Região Norte', 8210, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120001, 'Acrelândia', 'AC', 'Região Norte', 12538, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120005, 'Assis Brasil', 'AC', 'Região Norte', 6072, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120010, 'Brasiléia', 'AC', 'Região Norte', 21398, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120013, 'Bujari', 'AC', 'Região Norte', 8471, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120017, 'Capixaba', 'AC', 'Região Norte', 8798, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120020, 'Cruzeiro do Sul', 'AC', 'Região Norte', 78507, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120025, 'Epitaciolândia', 'AC', 'Região Norte', 15100, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120030, 'Feijó', 'AC', 'Região Norte', 32412, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120032, 'Jordão', 'AC', 'Região Norte', 6577, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120033, 'Mâncio Lima', 'AC', 'Região Norte', 15206, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120034, 'Manoel Urbano', 'AC', 'Região Norte', 7981, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120035, 'Marechal Thaumaturgo', 'AC', 'Região Norte', 14227, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120038, 'Plácido de Castro', 'AC', 'Região Norte', 17209, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120039, 'Porto Walter', 'AC', 'Região Norte', 9176, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120040, 'Rio Branco', 'AC', 'Região Norte', 336038, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120042, 'Rodrigues Alves', 'AC', 'Região Norte', 14389, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120043, 'Santa Rosa do Purus', 'AC', 'Região Norte', 4691, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120045, 'Senador Guiomard', 'AC', 'Região Norte', 20179, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120050, 'Sena Madureira', 'AC', 'Região Norte', 38029, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120060, 'Tarauacá', 'AC', 'Região Norte', 35590, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120070, 'Xapuri', 'AC', 'Região Norte', 16091, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(120080, 'Porto Acre', 'AC', 'Região Norte', 14880, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130002, 'Alvarães', 'AM', 'Região Norte', 14088, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130006, 'Amaturá', 'AM', 'Região Norte', 9467, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130008, 'Anamã', 'AM', 'Região Norte', 10214, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130010, 'Anori', 'AM', 'Região Norte', 16317, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130014, 'Apuí', 'AM', 'Região Norte', 18007, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130020, 'Atalaia do Norte', 'AM', 'Região Norte', 15153, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130030, 'Autazes', 'AM', 'Região Norte', 32135, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130040, 'Barcelos', 'AM', 'Região Norte', 25718, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130050, 'Barreirinha', 'AM', 'Região Norte', 27355, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130060, 'Benjamin Constant', 'AM', 'Região Norte', 33411, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130063, 'Beruri', 'AM', 'Região Norte', 15486, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130068, 'Boa Vista do Ramos', 'AM', 'Região Norte', 14979, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130070, 'Boca do Acre', 'AM', 'Região Norte', 30632, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130080, 'Borba', 'AM', 'Região Norte', 34961, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130083, 'Caapiranga', 'AM', 'Região Norte', 10975, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130090, 'Canutama', 'AM', 'Região Norte', 12738, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130100, 'Carauari', 'AM', 'Região Norte', 25774, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130110, 'Careiro', 'AM', 'Região Norte', 32734, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130115, 'Careiro da Várzea', 'AM', 'Região Norte', 23930, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130120, 'Coari', 'AM', 'Região Norte', 75965, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130130, 'Codajás', 'AM', 'Região Norte', 23206, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130140, 'Eirunepé', 'AM', 'Região Norte', 30665, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130150, 'Envira', 'AM', 'Região Norte', 16338, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130160, 'Fonte Boa', 'AM', 'Região Norte', 22817, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130165, 'Guajará', 'AM', 'Região Norte', 13974, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130170, 'Humaitá', 'AM', 'Região Norte', 44227, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130180, 'Ipixuna', 'AM', 'Região Norte', 22254, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130185, 'Iranduba', 'AM', 'Região Norte', 40781, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130190, 'Itacoatiara', 'AM', 'Região Norte', 86839, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130195, 'Itamarati', 'AM', 'Região Norte', 8038, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130200, 'Itapiranga', 'AM', 'Região Norte', 8211, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130210, 'Japurá', 'AM', 'Região Norte', 7326, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130220, 'Juruá', 'AM', 'Região Norte', 10802, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130230, 'Jutaí', 'AM', 'Região Norte', 17992, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130240, 'Lábrea', 'AM', 'Região Norte', 37701, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130250, 'Manacapuru', 'AM', 'Região Norte', 85141, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130255, 'Manaquiri', 'AM', 'Região Norte', 22801, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130260, 'Manaus', 'AM', 'Região Norte', 1802014, 'Metrópole');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130270, 'Manicoré', 'AM', 'Região Norte', 47017, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130280, 'Maraã', 'AM', 'Região Norte', 17528, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130290, 'Maués', 'AM', 'Região Norte', 52236, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130300, 'Nhamundá', 'AM', 'Região Norte', 18278, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130310, 'Nova Olinda do Norte', 'AM', 'Região Norte', 30696, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130320, 'Novo Airão', 'AM', 'Região Norte', 14723, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130330, 'Novo Aripuanã', 'AM', 'Região Norte', 21451, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130340, 'Parintins', 'AM', 'Região Norte', 102033, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130350, 'Pauini', 'AM', 'Região Norte', 18166, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130353, 'Presidente Figueiredo', 'AM', 'Região Norte', 27175, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130356, 'Rio Preto da Eva', 'AM', 'Região Norte', 25719, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130360, 'Santa Isabel do Rio Negro', 'AM', 'Região Norte', 18146, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130370, 'Santo Antônio do Içá', 'AM', 'Região Norte', 24481, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130380, 'São Gabriel da Cachoeira', 'AM', 'Região Norte', 37896, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130390, 'São Paulo de Olivença', 'AM', 'Região Norte', 31422, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130395, 'São Sebastião do Uatumã', 'AM', 'Região Norte', 10705, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130400, 'Silves', 'AM', 'Região Norte', 8444, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130406, 'Tabatinga', 'AM', 'Região Norte', 52272, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130410, 'Tapauá', 'AM', 'Região Norte', 19077, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130420, 'Tefé', 'AM', 'Região Norte', 61453, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130423, 'Tonantins', 'AM', 'Região Norte', 17079, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130426, 'Uarini', 'AM', 'Região Norte', 11891, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130430, 'Urucará', 'AM', 'Região Norte', 17094, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(130440, 'Urucurituba', 'AM', 'Região Norte', 17837, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140002, 'Amajari', 'RR', 'Região Norte', 9327, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140005, 'Alto Alegre', 'RR', 'Região Norte', 16448, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140010, 'Boa Vista', 'RR', 'Região Norte', 284313, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140015, 'Bonfim', 'RR', 'Região Norte', 10943, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140017, 'Cantá', 'RR', 'Região Norte', 13902, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140020, 'Caracaraí', 'RR', 'Região Norte', 18398, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140023, 'Caroebe', 'RR', 'Região Norte', 8114, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140028, 'Iracema', 'RR', 'Região Norte', 8696, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140030, 'Mucajaí', 'RR', 'Região Norte', 14792, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140040, 'Normandia', 'RR', 'Região Norte', 8940, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140045, 'Pacaraima', 'RR', 'Região Norte', 10433, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140047, 'Rorainópolis', 'RR', 'Região Norte', 24279, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140050, 'São João da Baliza', 'RR', 'Região Norte', 6769, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140060, 'São Luiz', 'RR', 'Região Norte', 6750, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(140070, 'Uiramutã', 'RR', 'Região Norte', 8375, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150010, 'Abaetetuba', 'PA', 'Região Norte', 141100, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150013, 'Abel Figueiredo', 'PA', 'Região Norte', 6780, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150020, 'Acará', 'PA', 'Região Norte', 53569, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150030, 'Afuá', 'PA', 'Região Norte', 35042, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150034, 'Água Azul do Norte', 'PA', 'Região Norte', 25057, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150040, 'Alenquer', 'PA', 'Região Norte', 52626, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150050, 'Almeirim', 'PA', 'Região Norte', 33614, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150060, 'Altamira', 'PA', 'Região Norte', 99075, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150070, 'Anajás', 'PA', 'Região Norte', 24759, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150080, 'Ananindeua', 'PA', 'Região Norte', 471980, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150085, 'Anapu', 'PA', 'Região Norte', 20543, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150090, 'Augusto Corrêa', 'PA', 'Região Norte', 40497, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150095, 'Aurora do Pará', 'PA', 'Região Norte', 26546, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150100, 'Aveiro', 'PA', 'Região Norte', 15849, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150110, 'Bagre', 'PA', 'Região Norte', 23864, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150120, 'Baião', 'PA', 'Região Norte', 36882, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150125, 'Bannach', 'PA', 'Região Norte', 3431, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150130, 'Barcarena', 'PA', 'Região Norte', 99859, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150140, 'Belém', 'PA', 'Região Norte', 1393399, 'Metrópole');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150145, 'Belterra', 'PA', 'Região Norte', 16318, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150150, 'Benevides', 'PA', 'Região Norte', 51651, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150157, 'Bom Jesus do Tocantins', 'PA', 'Região Norte', 15298, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150160, 'Bonito', 'PA', 'Região Norte', 13630, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150170, 'Bragança', 'PA', 'Região Norte', 113227, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150172, 'Brasil Novo', 'PA', 'Região Norte', 15690, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150175, 'Brejo Grande do Araguaia', 'PA', 'Região Norte', 7317, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150178, 'Breu Branco', 'PA', 'Região Norte', 52493, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150180, 'Breves', 'PA', 'Região Norte', 92860, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150190, 'Bujaru', 'PA', 'Região Norte', 25695, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150195, 'Cachoeira do Piriá', 'PA', 'Região Norte', 26484, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150200, 'Cachoeira do Arari', 'PA', 'Região Norte', 20443, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150210, 'Cametá', 'PA', 'Região Norte', 120896, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150215, 'Canaã Dos Carajás', 'PA', 'Região Norte', 26716, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150220, 'Capanema', 'PA', 'Região Norte', 63639, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150230, 'Capitão Poço', 'PA', 'Região Norte', 51893, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150240, 'Castanhal', 'PA', 'Região Norte', 173149, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150250, 'Chaves', 'PA', 'Região Norte', 21005, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150260, 'Colares', 'PA', 'Região Norte', 11381, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150270, 'Conceição do Araguaia', 'PA', 'Região Norte', 45557, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150275, 'Concórdia do Pará', 'PA', 'Região Norte', 28216, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150276, 'Cumaru do Norte', 'PA', 'Região Norte', 10466, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150277, 'Curionópolis', 'PA', 'Região Norte', 18288, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150280, 'Curralinho', 'PA', 'Região Norte', 28549, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150285, 'Curuá', 'PA', 'Região Norte', 12254, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150290, 'Curuçá', 'PA', 'Região Norte', 34294, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150293, 'Dom Eliseu', 'PA', 'Região Norte', 51319, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150295, 'Eldorado Dos Carajás', 'PA', 'Região Norte', 31786, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150300, 'Faro', 'PA', 'Região Norte', 8177, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150304, 'Floresta do Araguaia', 'PA', 'Região Norte', 17768, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150307, 'Garrafão do Norte', 'PA', 'Região Norte', 25034, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150309, 'Goianésia do Pará', 'PA', 'Região Norte', 30436, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150310, 'Gurupá', 'PA', 'Região Norte', 29062, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150320, 'Igarapé-açu', 'PA', 'Região Norte', 35887, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150330, 'Igarapé-miri', 'PA', 'Região Norte', 58077, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150340, 'Inhangapi', 'PA', 'Região Norte', 10037, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150345, 'Ipixuna do Pará', 'PA', 'Região Norte', 51309, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150350, 'Irituia', 'PA', 'Região Norte', 31364, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150360, 'Itaituba', 'PA', 'Região Norte', 97493, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150370, 'Itupiranga', 'PA', 'Região Norte', 51220, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150375, 'Jacareacanga', 'PA', 'Região Norte', 14103, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150380, 'Jacundá', 'PA', 'Região Norte', 51360, 'Médio');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150390, 'Juruti', 'PA', 'Região Norte', 47086, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150400, 'Limoeiro do Ajuru', 'PA', 'Região Norte', 25021, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150405, 'Mãe do Rio', 'PA', 'Região Norte', 27904, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150410, 'Magalhães Barata', 'PA', 'Região Norte', 8115, 'Pequeno I');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150420, 'Marabá', 'PA', 'Região Norte', 233669, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150430, 'Maracanã', 'PA', 'Região Norte', 28376, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150440, 'Marapanim', 'PA', 'Região Norte', 26605, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150442, 'Marituba', 'PA', 'Região Norte', 108246, 'Grande');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150445, 'Medicilândia', 'PA', 'Região Norte', 27328, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150450, 'Melgaço', 'PA', 'Região Norte', 24808, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150460, 'Mocajuba', 'PA', 'Região Norte', 26731, 'Pequeno II');
insert into cidade(ibge, nome, estado, regiao, populacao, porte) values(150470, 'Moju', 'PA', 'Região Norte', 70018, 'Médio');
